### PR TITLE
Manually starting GPS and opening a recorded track bug fixed. Fixes #200.

### LINKED ISSUE #200: Manually starting GPS and opening a recorded track
__Actual question:__ do we need the functionality to start the GPS before a recording is started? (the GPS icon in the action menu; disabled from v3.7.+).

IMG_20200429_212216

**To Reproduce**
1. No recording is running
2. TrackListActivity: go to menu and start click start GPS
3. Open an already recorded track
4. TrackDetailActivity opens, but shows UI for recording a track
(should just open and just present the recorded track in non-recording mode).

Bug was introduced while adding the "resume track"-feature.

**Technical information**
 - Version v3.6.0 and upwards

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
I've fixed the #200 

Only starts a new record if "someone" request it (resume track option is clicked or record button is clicked).

**Link to the the issue**
#200 

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

File: src/main/java/de/dennisguse/opentracks/TrackListActivity.java [hunk 1]
```diff
@@ -205,7 +205,7 @@ public void onClick(View v) {
             if (!PreferencesUtils.isRecording(recordingTrackId)) {
                 // Not recording -> Recording
                 updateMenuItems(false, true);
-                Intent newIntent = IntentUtils.newIntent(TrackListActivity.this, TrackDetailActivity.class);
+                Intent newIntent = IntentUtils.newIntent(TrackListActivity.this, TrackDetailActivity.class).putExtra(TrackDetailActivity.EXTRA_RECORDING_REQUEST, true);
```
Comment (dennisguse) [inline src/main/java/de/dennisguse/opentracks/TrackListActivity.java:208]: That is somehow implicit and hard to see.
Can we somehow make this easier to read?

Comment (rgmf) [reply src/main/java/de/dennisguse/opentracks/TrackListActivity.java:208]: I've reviewed code before resume option and I've followed the same approach. Before, TrackListActivity used a flag called `startNewRecording` to know if user had been clicked on record button to start a recording, so if user clicked on Start GPS button it has not start recording because `startNewRecording == false`.

Now, TrackDetailActivity uses a flag called `isRecordingRequest` to know if it has to start a recording. So, if an Activity wants to start a new recording must starts TrackDetailActivity passing true in the extra argument EXTRA_RECORDING_REQUEST.

Then, if someone want to use TrackDetailActivity should understand what EXTRA_ data is for. Yes, that become code a harder one.

TrackListActivity and TrackDetailActivity need to "speak" each other. The other option is doing so through Service and the logic become harder.

I can't think of anything better, some clue may help. Anyway, I can give this a spin.

---

Offtopic: Maybe https://github.com/OpenTracksApp/OpenTracks/issues/171 is an option to simplify all this. With TrackListActivity, TrackDetailActivity and TrackRecordActivity could be more simple.

Comment (dennisguse) [reply src/main/java/de/dennisguse/opentracks/TrackListActivity.java:208]: I just meant the long line :)
It is so easy to overlook this additional putExtra.

#171: I totally agree.

**Comment by dennisguse** [comment]
@rgmf Nicely done; merge whenever it feels right :)

**Comment by dennisguse** [comment]
Should we create a new release?

**Comment by rgmf** [comment]
> Should we create a new release?

Yes, you can create a new release to include it. It works, I tested it yesterday and all works well.
