### PR TITLE
Bug: StatisticsRecordingFragment: speed and location where sometimes 0.

### LINKED ISSUE #628: Speed and elevation correctly shown while recording
**Describe the bug**
When I start a new track current speed is always 0 and elevation is "-". Anyway, all stats are computed correctly. I've not realized until today so I don't know when this problem begin (usually I start a record and save the smartphone in my pocket).

Is it reproducible for someone? It's an strange error so I don't know if it's an OT issue or a fault of my smartphone.

PS/ I cannot reproduce it in a virtual device :(

Here there is a screenshots:
imagen

**More info**
I'm not using any sensor.

**Technical information**
 - Device: Pixel XL 2
 - OS: LineageOS 17.1
 - Version: current F-Droid version (3.15.0)

### PR DESCRIPTION
**Pull request by dennisguse**
Fixes #628.

The TrackDataHub not send notification if no TrackPoints were processed.

### CODE REVIEW

File: src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java [hunk 1]
```diff
@@ -412,8 +412,10 @@ private void notifyTrackPointsTableUpdate(boolean updateSamplingState, Set<Track
             lastSeenTrackPointId = localLastSeenTrackPointIdId;
         }
 
-        for (TrackDataListener listener : sampledInListeners) {
-            listener.onNewTrackPointsDone(trackPoint);
+        if (trackPoint != null) {
```
Comment (rgmf) [inline src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: This works but speed maintains the last speed if OT loses the GPS signal instead of resetting the speed to 0.

Look at this (screenshots when OT loses GPS - the speed should be 0):

imagen

Comment (dennisguse) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: Valid point. Have not thought about this one...

Comment (dennisguse) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: After 5min thinking about it: I am not sure if this is an issue.
I mean, if I set the GPS recording time interval to 30min, what speed do I expect after 5min?
Is it the speed of the initial GPS reading or 0?

On the other hand, we have TrackPoint.isRecent() with a fixed timeout of 1 minute.
Anyhow, this functionality must be triggered by the _updateUIeachSecond_-Runnable.

Comment (rgmf) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:420]: For me is not a problem, I mean this doesn't disturb me but I thought it could be an actual issue.
So, okay for me :clap:

Comment (rgmf) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:420]: And what you say has a lot of sense ;)

Comment (dennisguse) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: I added a commit that should (not tested it), reset the speed if the trackpoint is outdated (set it to 0) and if sensor data is present set it to it's value.

Comment (rgmf) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: I'm running it and I get this error when I try to start a new record:

```
2021-03-05 18:41:48.849 22986-23014/de.dennisguse.opentracks.debug E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2021-03-05 18:42:04.963 22986-22986/de.dennisguse.opentracks.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dennisguse.opentracks.debug, PID: 22986
    java.lang.RuntimeException: Unable to create service de.dennisguse.opentracks.services.TrackRecordingService: java.lang.NullPointerException: Attempt to invoke virtual method 'long de.dennisguse.opentracks.content.data.Track$Id.getId()' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long de.dennisguse.opentracks.content.data.Track$Id.getId()' on a null object reference
        at de.dennisguse.opentracks.content.provider.ContentProviderUtils.getTrack(ContentProviderUtils.java:205)
        at de.dennisguse.opentracks.services.TrackRecordingService.restartTrackAfterServiceRestart(TrackRecordingService.java:347)
        at de.dennisguse.opentracks.services.TrackRecordingService.onCreate(TrackRecordingService.java:153)
```

Comment (rgmf) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: Forget what I wrote (I'v just deleted it)... Android Studio got messy or something like this.

All okay.

Comment (rgmf) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: Just out of curiosity: why TrackPoint.MAX_LOCATION_AGE == 1 minute? Is there science behind this?

Comment (dennisguse) [reply src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java:415]: No clue, but I guess it had.
But as the knowledge was lost - we can do whatever we believe is the right choice ;)

**Review by rgmf — APPROVED** [review]
